import './globals.css'
import { Sidebar } from '@/components/Sidebar'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased scrollbar-thin scrollbar-track-zinc-100 scrollbar-thumb-zinc-500 scrollbar-thumb-rounded-full`}
      >
        <Providers>
          <main className="min-h-screen dark:bg-zinc-900 lg:grid lg:grid-cols-app ">
            <Sidebar />
            <div className="max-w-screen px-4 pb-12 pt-24 lg:col-start-2 lg:px-8 lg:pt-8">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
